/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'secretId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const ReactionCounts = IDL.Record({
  'sad' : IDL.Nat,
  'wow' : IDL.Nat,
  'heart' : IDL.Nat,
  'fire' : IDL.Nat,
});
export const Secret = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
  'reactions' : ReactionCounts,
});
export const SecretPreview = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'commentCount' : IDL.Nat,
  'reactions' : ReactionCounts,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [IDL.Nat], []),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getSecret' : IDL.Func([IDL.Nat], [Secret], ['query']),
  'getSecrets' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(SecretPreview)],
      ['query'],
    ),
  'reactToSecret' : IDL.Func([IDL.Nat, IDL.Text], [ReactionCounts], []),
  'submitSecret' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'secretId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const ReactionCounts = IDL.Record({
    'sad' : IDL.Nat,
    'wow' : IDL.Nat,
    'heart' : IDL.Nat,
    'fire' : IDL.Nat,
  });
  const Secret = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
    'reactions' : ReactionCounts,
  });
  const SecretPreview = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'commentCount' : IDL.Nat,
    'reactions' : ReactionCounts,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [IDL.Nat], []),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getSecret' : IDL.Func([IDL.Nat], [Secret], ['query']),
    'getSecrets' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(SecretPreview)],
        ['query'],
      ),
    'reactToSecret' : IDL.Func([IDL.Nat, IDL.Text], [ReactionCounts], []),
    'submitSecret' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };