/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'text' : string,
  'secretId' : bigint,
  'timestamp' : bigint,
}
export interface ReactionCounts {
  'sad' : bigint,
  'wow' : bigint,
  'heart' : bigint,
  'fire' : bigint,
}
export interface Secret {
  'id' : bigint,
  'text' : string,
  'timestamp' : bigint,
  'commentCount' : bigint,
  'category' : string,
  'reactions' : ReactionCounts,
}
export interface SecretPreview {
  'id' : bigint,
  'text' : string,
  'commentCount' : bigint,
  'reactions' : ReactionCounts,
}
export interface _SERVICE {
  'addComment' : ActorMethod<[bigint, string, bigint], bigint>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getSecret' : ActorMethod<[bigint], Secret>,
  'getSecrets' : ActorMethod<[string, bigint], Array<SecretPreview>>,
  'reactToSecret' : ActorMethod<[bigint, string], ReactionCounts>,
  'submitSecret' : ActorMethod<[string, string, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];